pipeline {
    agent any

    stages {
        stage('Pull Code') {
            steps {
                echo 'Skipping code checkout because image already built'
            }
        }

        stage('Build Docker Image') {
            steps {
                echo 'Building Docker Image...'
                bat 'docker build -t front-end:latest ./frontend'
            }
        }

        stage('Run Docker Container') {
            steps {
                echo 'Running Docker Container...'
                bat '''
                docker stop frontend-container
                docker rm frontend-container
                '''
                bat 'docker run -d -p 3000:80 --name frontend-container front-end:latest'
            }
        }
    }
}
