services:
  # Backend Service (Node.js API)
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      # Map host port 5050 to container port 5050
      - "5050:5050"
    environment:
      # Environment variables - Using MongoDB Atlas instead of local mongo
      - NODE_ENV=production
      - PORT=5050
      - MONGO_URI=mongodb+srv://yanushkakumaar:D5hGHSieYM6CFaXx@cluster0.blnzamp.mongodb.net/todoDB?retryWrites=true&w=majority&appName=Cluster0
      - JWT_SECRET=12345
    networks:
      - app-network
    restart: unless-stopped

  # Frontend Service (React App)
  frontend:
    build:
      # The context is now the 'App' directory where the frontend code lives
      context: ./App
      # The Dockerfile should be inside the 'App' directory as well
      dockerfile: frontend.Dockerfile
    ports:
      # Map host port 3000 to container port 80 (Nginx)
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

# Define the network
networks:
  app-network:
    driver: bridge

# Note: Removed mongo service and mongo-data volume since we're using MongoDB Atlas